language: objective-c
cache: cocoapods # pod install somtimes takes >20 minutes, so lets cache this

osx_image: xcode8

env:
  -EARLY_START_SIMULATOR=1 # early starting simulator reduces false negatives due to test timeouts

before_install:
    - brew update # we may not be running the latest version so always update
    - brew outdated xctool || brew upgrade xctool # only upgrade if outdated (saves 2 minutes)
    - gem install cocoapods # get the latest cocoapods
    - gem install xcpretty
    - pod repo update --silent # log output is too long without --silent

install: travis_wait 30 pod install # OpenSSL takes a long time to compile

script: make ci

